  - name: Add the user 
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete {{ component }} file
    ansible.builtin.file:
      path: /tmp/{{ component }}.zip
      state: absent

  - name: Download the {{ component }} application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
      dest: /tmp/{{ component }}.zip

  - name: Extract {{ component }} application
    ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes